"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY', 'django-insecure-2(=4(qe@!!b(o8@5-!q2qlr!23v3=uxfunuc*ipk3w*jwu^22x'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'stations',
    'routeplanner',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
#
# DATABASE_URL (set by docker-compose to point at the postgres service) takes
# priority; falls back to a local sqlite file so `python manage.py runserver`
# still works with zero setup for anyone not using Docker.

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': ('rest_framework.renderers.JSONRenderer',),
    'DEFAULT_PARSER_CLASSES': ('rest_framework.parsers.JSONParser',),
}

# Only wide open in DEBUG (the default locally) -- lets a local static HTML
# test page call the API directly from a file:// or different-port origin.
# Never permissive in a real deployment, where DJANGO_DEBUG=false.
CORS_ALLOW_ALL_ORIGINS = DEBUG

# --- Cache (Redis in production/docker-compose; falls back to an in-process
# local-memory cache with zero setup when REDIS_URL isn't set) ---
REDIS_URL = os.environ.get('REDIS_URL')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }

# --- External routing/geocoding services (both free, no API key required) ---
OSRM_BASE_URL = os.environ.get('OSRM_BASE_URL', 'https://router.project-osrm.org')
NOMINATIM_BASE_URL = os.environ.get('NOMINATIM_BASE_URL', 'https://nominatim.openstreetmap.org')
NOMINATIM_USER_AGENT = os.environ.get(
    'NOMINATIM_USER_AGENT', 'FleetFuelPlanner/1.0 (contact: alfonso.altamar@tesote.com)'
)

# Place coordinates are effectively permanent; routes are stable but could
# shift with traffic-independent map updates, so a shorter TTL is used.
GEOCODE_CACHE_TTL_SECONDS = int(os.environ.get('GEOCODE_CACHE_TTL_SECONDS', 60 * 60 * 24 * 30))
ROUTE_CACHE_TTL_SECONDS = int(os.environ.get('ROUTE_CACHE_TTL_SECONDS', 60 * 60))

# --- Trip / vehicle assumptions (documented in README) ---
VEHICLE_MAX_RANGE_MILES = float(os.environ.get('VEHICLE_MAX_RANGE_MILES', 500))
VEHICLE_MPG = float(os.environ.get('VEHICLE_MPG', 10))
ROUTE_CORRIDOR_BUFFER_MILES = float(os.environ.get('ROUTE_CORRIDOR_BUFFER_MILES', 25))

# Fixed economic cost of making a stop (driver time + detour, ~20-30 min).
# Used as an optimization weight so the planner doesn't recommend
# pocket-change top-offs; it is NOT included in the reported fuel cost.
STOP_COST_USD = float(os.environ.get('STOP_COST_USD', 15))

# Per-strategy stop-cost weights for the `strategy` request field:
# cheapest_fuel ignores the cost of stopping (pure price optimization),
# fewest_stops weighs it heavily (time optimization), balanced is the default.
FUEL_STRATEGY_STOP_COSTS = {
    'cheapest_fuel': 0.0,
    'balanced': STOP_COST_USD,
    'fewest_stops': float(os.environ.get('FEWEST_STOPS_COST_USD', 75)),
}

# Safety reserve: the plan never lets the tank dip below this many miles of
# range, neither between stops nor at arrival. Usable range per fill is
# therefore VEHICLE_MAX_RANGE_MILES - FUEL_RESERVE_MILES.
FUEL_RESERVE_MILES = float(os.environ.get('FUEL_RESERVE_MILES', 60))
